somnambulist_api:
    exception_handler:
        converters:
            Assert\InvalidArgumentException: Somnambulist\Bundles\ApiBundle\Response\ExceptionConverters\AssertionExceptionConverter
            Assert\LazyAssertionException: Somnambulist\Bundles\ApiBundle\Response\ExceptionConverters\LazyAssertionExceptionConverter
            Symfony\Component\Messenger\Exception\HandlerFailedException: Somnambulist\Bundles\ApiBundle\Response\ExceptionConverters\HandlerFailedExceptionConverter
    request_handler:
        per_page: 20
        max_per_page: 100
        limit: 100
    subscribers:
        exception_to_json: true
        json_to_post: true

somnambulist_read_models:
    connections:
        default: 'doctrine.dbal.default_connection'

somnambulist_form_request:
    subscribers:
        authorization: true
        form_validation: true
