
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Somnambulist\Components\Domain\Events\Publishers\DoctrineEventPublisher:
        tags: ['doctrine.event_subscriber']

    Somnambulist\Components\Domain\Events\Adapters\DomainEventNormalizer:

    somnambulist.domain.event_serializer:
        alias: Somnambulist\Components\Domain\Events\Adapters\MessengerSerializer

    Somnambulist\Components\Domain\Commands\CommandBus:
        alias: Somnambulist\Components\Domain\Commands\Adapters\MessengerCommandBus
        public: true

    Somnambulist\Components\Domain\Commands\Adapters\MessengerCommandBus:

    Somnambulist\Components\Domain\Events\EventBus:
        alias: Somnambulist\Components\Domain\Events\Adapters\MessengerEventBus
        public: true

    Somnambulist\Components\Domain\Jobs\Adapters\MessengerJobQueue:

    Somnambulist\Components\Domain\Jobs\JobQueue:
        alias: Somnambulist\Components\Domain\Jobs\Adapters\MessengerJobQueue
        public: true

    Somnambulist\Components\Domain\Events\Adapters\MessengerEventBus:

    Somnambulist\Components\Domain\Queries\QueryBus:
        alias: Somnambulist\Components\Domain\Queries\Adapters\MessengerQueryBus
        public: true

    Somnambulist\Components\Domain\Queries\Adapters\MessengerQueryBus:

    Somnambulist\Bundles\ApiBundle\ArgumentResolvers\:
        resource: '../../vendor/somnambulist/api-bundle/src/ArgumentResolvers/'
        tags:
            - { name: controller.argument_value_resolver, priority: 105 }
